// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPg8URUK_w97Dw4JtJMvSdaGqVak3vPA',
    appId: '1:533966941058:web:73f0717952c601a90dfd9b',
    messagingSenderId: '533966941058',
    projectId: 'gossip-thedevpiyush',
    authDomain: 'gossip-thedevpiyush.firebaseapp.com',
    storageBucket: 'gossip-thedevpiyush.appspot.com',
    measurementId: 'G-FCS8EMDBEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjNQViyeXoM2Muujs2vmjZndSQ_tmp0E',
    appId: '1:533966941058:android:19c97622dbd9f3d90dfd9b',
    messagingSenderId: '533966941058',
    projectId: 'gossip-thedevpiyush',
    storageBucket: 'gossip-thedevpiyush.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXMvFnt0cPs4zUaYi6e1pefsvqeorwEk',
    appId: '1:533966941058:ios:4a217ce165934f140dfd9b',
    messagingSenderId: '533966941058',
    projectId: 'gossip-thedevpiyush',
    storageBucket: 'gossip-thedevpiyush.appspot.com',
    androidClientId: '533966941058-60thvog3qs39ll6i38qfl01ungvmfh4i.apps.googleusercontent.com',
    iosClientId: '533966941058-4i4jndtemhks2p9etel1arhka363l7bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMXMvFnt0cPs4zUaYi6e1pefsvqeorwEk',
    appId: '1:533966941058:ios:a91a88c2a6c58d840dfd9b',
    messagingSenderId: '533966941058',
    projectId: 'gossip-thedevpiyush',
    storageBucket: 'gossip-thedevpiyush.appspot.com',
    androidClientId: '533966941058-60thvog3qs39ll6i38qfl01ungvmfh4i.apps.googleusercontent.com',
    iosClientId: '533966941058-aei47e4trt0k75qbol454sond7n33ih1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
